# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: ecommerce
    hostname: host-mongo
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

